FROM --platform=$TARGETOS/$TARGETARCH node:20-bookworm-slim

LABEL author="Jamie Hatton" maintainer="jamie@hss.gg"

RUN apt update \
	&& apt -y install pkg-config ffmpeg iproute2 git sqlite3 libsqlite3-dev python3 python3-dev ca-certificates dnsutils tzdata zip tar curl build-essential libtool libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libpixman-1-dev python-is-python3 \
	# Additional dependencies for headless Chrome
	chromium xvfb libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libatk-bridge2.0-0 libpangocairo-1.0-0 libgtk-3-0 \
	&& npm -g install npm@latest \
	&& useradd -m -d /home/container container

# Set environment variables to help with native module builds
ENV CXXFLAGS=--std=c++17

# Set environment variables for Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./../entrypoint.sh /entrypoint.sh
CMD [ "/bin/bash", "/entrypoint.sh" ]
