name: build deno
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 14,28 * *"
  push:
    branches:
      - master
    paths:
      - deno/**
jobs:
  push:
    name: "yolks:deno_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
    steps:
      - uses: actions/checkout@v2
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./deno
          file: ./deno/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/wumpushost/yolks:deno_${{ matrix.tag }}
