name: build dotnet
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 14,28 * *"
  push:
    branches:
      - master
    paths:
      - dotnet/**
jobs:
  push:
    name: "yolks:dotnet_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 5
          - 6
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./dotnet
          file: ./dotnet/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/wumpushost/yolks:dotnet_${{ matrix.tag }}
