name: build go
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 14,28 * *"
  push:
    branches:
      - master
    paths:
      - go/**
jobs:
  push:
    name: "yolks:go_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 1.18
          - 1.19
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: docker.hextro.host
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./go
          file: ./go/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.hextro.host/yolks:go_${{ matrix.tag }}
