name: build mono
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 14,28 * *"
  push:
    branches:
      - master
    paths:
      - mono/**
jobs:
  push:
    name: "yolks:mono_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./mono
          file: ./mono/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/wumpushost/yolks:mono_${{ matrix.tag }}
