name: build nodejs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 14,28 * *"
  push:
    branches:
      - master
    paths:
      - nodejs/**
jobs:
  push:
    name: "yolks:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 16
          - 18
          - 19
    steps:
      - uses: actions/checkout@v2
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: docker.lightbulb.host
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.lightbulb.host/yolks:nodejs_${{ matrix.tag }}
